site_name: CATÁLOGO DE PROMPTS
theme:
  name: material
  features:
    - content.code.copy
    # - navigation.sections
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal    
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
nav:
    # - Index: index.md
    - SEMÁNTICA DE ENTRADA:
      - Patrón de Creación de Metalenguaje: Patron-de-Creacion-de-Metalenguaje.md
    - PERSONALIZACIÓN DE SALIDA:
      - Automatizador de Salida: Automatizador-de-Salida.md
      - Patrón Persona: Patron-Persona.md
      - Patrón Generador de Visualización: Patron-Generador-de-Visualizacion.md
      - Patrón Receta: Patron-Receta.md
      - Patrón de Plantilla: Patron-de-Plantilla.md
      - Patrón De Público Objetivo: Patron-De-Publico-Objetivo.md
    - IDENTIFICACIÓN DE ERRORES:
      - Patrón de Lista de Verificación de Hechos: Patron-de-Lista-de-Verificacion-de-Hechos.md
      - Patrón de Reflexión: Patron-de-Reflexion.md
    - MEJORA DEL PROMPT:
      - Patrón de Refinamiento de Pregunta: Patron-de-Refinamiento-de-Pregunta.md
      - Patrón de Enfoques Alternativos: Patron-de-Enfoques-Alternativos.md
      - Patrón de Verificador Cognitivo: Patron-de-Verificador-Cognitivo.md
      - Patrón Rompedor de Rechazo: Patron-Rompedor-de-Rechazo.md
    - INTERACCIÓN:
      - Patrón de Interacción Invertida: Patron-de-Interaccion-Invertida.md            
      - Patrón Juego: Patron-Juego.md
      - Patrón de Generación Infinita: Patron-de-Generacion-Infinita.md
    - CONTROL DE CONTEXTO:
      - Patrón Gestor de Contexto: Patron-Gestor-de-Contexto.md